package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/mwing/isolated-dev/go/internal/devcontainer"
	"github.com/mwing/isolated-dev/go/internal/project"
	"github.com/mwing/isolated-dev/go/internal/trust"
)

func newDevcontainerCmd(env *Env) *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "devcontainer",
		Short: "Write a devcontainer.json describing this project's environment",
		Long: "Exports what dev2 builds as a .devcontainer/devcontainer.json, so\n" +
			"someone who opens the repository in an editor gets the same image,\n" +
			"the same tools and the same unprivileged user without installing\n" +
			"this tool.\n\n" +
			"It does not export the sandbox. Egress filtering lives in a proxy\n" +
			"sidecar dev2 starts, and an editor will not start it — an exported\n" +
			"container has ordinary network access. The generated file says so\n" +
			"in a comment, because a teammate who believes otherwise is worse\n" +
			"off than one who never had the file.\n\n" +
			"dev2 already reads a devcontainer.json when a project has one, so\n" +
			"this is the other direction: for teams where not everyone uses\n" +
			"dev2.",
		Args: cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			return writeDevcontainer(env, force)
		},
	}
	cmd.Flags().BoolVar(&force, "force", false, "overwrite existing files")
	return cmd
}

// generatedHeader marks a Dockerfile this command wrote.
const generatedHeader = "# Generated by `dev2 devcontainer`"

// dropGenerated makes regeneration read the project rather than the last
// export of it.
//
// Once a devcontainer is written, dev2 finds it and builds from it — which
// is the intent, since both tools then build one description. But
// regenerating from that output would render a template into a file that
// is already the render, appending the tools layer a second time and the
// upgrade a second time, growing with every run. The generated file is
// output, so for the purpose of producing it, it does not exist.
func dropGenerated(p *project.Project) {
	if p.Dockerfile == "" {
		return
	}
	if filepath.Base(filepath.Dir(p.Dockerfile)) != ".devcontainer" {
		return
	}
	raw, err := os.ReadFile(p.Dockerfile)
	if err != nil || !strings.HasPrefix(string(raw), generatedHeader) {
		return
	}
	p.Dockerfile = ""
	p.DevcontainerImage = ""
	p.FromTemplate = p.Detected.Found()
}

func writeDevcontainer(env *Env, force bool) error {
	cfg, p, err := resolveProject(env)
	if err != nil {
		return err
	}
	dropGenerated(p)

	// Tools accepted on this machine count as much as tools the project
	// requests: both are in the image dev2 builds, so both belong in a
	// file that claims to describe it.
	store, err := trust.Load(env.Paths.Home, p.Dir)
	if err != nil {
		return err
	}
	tools := effectiveTools(cfg, store)

	opts := devcontainer.Options{
		Name:           p.Name,
		Ports:          p.Ports,
		Tools:          tools,
		EgressFiltered: p.Network == project.NetworkAllowlist,
	}

	switch {
	case p.DevcontainerImage != "" && len(tools) == 0:
		// The project already names an image and adds nothing to it, so
		// pointing at that image is both simpler and more honest than
		// generating a Dockerfile that only repeats it.
		opts.Image = p.DevcontainerImage
	case p.Dockerfile != "" && len(tools) == 0 && len(cfg.Pins) == 0 &&
		!cfg.UpgradePackages:
		// The project's own Dockerfile is built as-is, so reference it
		// rather than copying: a copy is a second thing to keep in step.
		rel, relErr := filepath.Rel(p.Dir, p.Dockerfile)
		if relErr != nil {
			return relErr
		}
		opts.DockerfilePath = filepath.Join("..", rel)
	default:
		// Anything dev2 adds — a rendered template, digests, upgraded
		// packages, tools — has to be materialized, or the exported
		// environment is not the one dev2 builds.
		dockerfile, dferr := p.RenderedDockerfile()
		if dferr != nil {
			return dferr
		}
		dockerfile = project.ApplyPins(dockerfile, cfg.Pins)
		if cfg.UpgradePackages {
			dockerfile = project.WithPackageUpgrade(dockerfile)
		}
		if len(tools) > 0 {
			sorted := append([]string(nil), tools...)
			sort.Strings(sorted)
			// The tools overlay is a separate build FROM the project
			// image; flattened into one file it is the same layers minus
			// its own FROM.
			overlay := project.ToolsDockerfile("", sorted)
			if _, rest, ok := strings.Cut(overlay, "\n"); ok {
				dockerfile = strings.TrimRight(dockerfile, "\n") + "\n\n" + rest
			}
		}
		opts.Dockerfile = generatedHeader + ". Regenerate rather than edit.\n" + dockerfile
	}

	g := devcontainer.Generate(opts)

	paths := make([]string, 0, len(g.Files))
	for rel := range g.Files {
		paths = append(paths, rel)
	}
	sort.Strings(paths)

	var conflicts []string
	for _, rel := range paths {
		if _, statErr := os.Stat(filepath.Join(p.Dir, rel)); statErr == nil {
			conflicts = append(conflicts, rel)
		}
	}
	if len(conflicts) > 0 && !force {
		return fmt.Errorf("%s already exists in %s; use --force to overwrite",
			strings.Join(conflicts, ", "), p.Dir)
	}

	for _, rel := range paths {
		full := filepath.Join(p.Dir, rel)
		if mkErr := os.MkdirAll(filepath.Dir(full), 0o755); mkErr != nil {
			return mkErr
		}
		if wErr := os.WriteFile(full, []byte(g.Files[rel]), 0o644); wErr != nil {
			return wErr
		}
		fmt.Fprintf(env.Stdout, "  %s\n", rel)
	}

	fmt.Fprintln(env.Stdout)
	for _, note := range g.Notes {
		fmt.Fprintf(env.Stdout, "Note: %s\n", note)
	}
	fmt.Fprintln(env.Stdout, "\nCommit it: a teammate without dev2 then gets the same "+
		"environment from their editor.")
	return nil
}
